keep month, year, newmoonnumber columns correct in forecasts
weecology/portalPredictions pull request #120
Opened 2017-11-01 20:21 UTC by emchristensen

this should fix issue #110 
wrote a function to pull next 12 newmoondates from navy.mil, so when forecasting using PortalForecasts the month, year, and newmoonnumber columns remain in sync
PortalHindcasts had the same problem, fixed that too

2017-11-06 14:47 UTC, sdtaylor commented
Couldn't we populate the `moon_dates.csv` file with every newmoon for a decade or so into the future? That seems easier than querying for it every time this runs.

2017-11-06 20:28 UTC, gmyenni commented
We've decided to update tables in PortalData like `moon_dates.csv` as new data comes in, rather than project them out past existing data.

If you want a `moon_dates` that goes a decade into the future, we could have one here in portalPredictions. . .

2017-11-06 21:04 UTC, emchristensen commented
Does looking it up every time slow down the code?  Populating a table for an arbitrary time period like a decade without some mechanism for updating it seems like creating problems for future people.  Maybe we can have Travis check it periodically and update it if necessary?

2017-11-06 21:55 UTC, sdtaylor commented
I only suggest that because it's something that should never change once you get it once. If they can predict solar eclipses decades in advance then their new moon dates are probably solid.

2017-11-08 15:23 UTC, sdtaylor requested changes
This looks good. I just put some suggestions to make it easier to follow.

2017-11-08 15:23 UTC, sdtaylor commented on models/model_functions.R
Need a comment here such as
```
# Returns a data.frame of newmoons in the future in the same format of moons
# moons is the output of get_moon_data()
```

2017-11-08 15:23 UTC, sdtaylor commented on PortalForecasts.R
>  moons = get_moon_data()
add comment here like in portalhindcasts

```
# #get dates of 12 new moons following newmoon of interest
```

2017-11-08 15:23 UTC, sdtaylor commented on models/model_functions.R
> +  year = tail(moons$year,1)
change these to `most_recent_year` and `most_recent_month` to be more descriptive

2017-11-08 19:09 UTC, emchristensen commented
Ok @sdtaylor I tried to incorporate all your edits -- give it another look and see what you think

2017-11-08 19:38 UTC, sdtaylor approved these changes

2017-11-08 19:42 UTC, merged