Interpolate pev garch
weecology/portalPredictions pull request #212
Opened 2018-02-07 06:39 UTC by DAPPERstats

this branch updates the pois_env_ts model to include data interpolation and to also include a no-covariate (i.e. intercept only) model
the model is now renamed to pevGARCH (this is a Poisson environmental variate GARCH model)

associated with the model update, there is also an update to the get_weather_data function to produce the weather data associated with each new moon (even if there was no census, in order to match the interpolated abundances values) as well.

2018-02-08 17:21 UTC, ethanwhite requested changes
Looks great overall. The one major thing is that the idea behind all of the lag code is unclear. Some comments to explain what it's doing would be useful. I also made a couple of minor cleanup suggestions.

Hopefully we can get these added today so this can be merged in before tomorrow's forecast build.

2018-02-08 18:18 UTC, DAPPERstats commented on models/pevgarch.R
> +    zero_abund_interval <- matrix(0, ncol = 2, nrow = 12)
ooh good catch on that! 
this actually also is tied with the argument to the model function named `num_forecast_newmoons` which has been hardcoded as 12 in all the models, but should be based on the length of `forecast_months` that comes out of the metadata
i'll address this here, and will go back to the other models to tidy that as well.

2018-02-08 18:31 UTC, DAPPERstats commented
I just added a bit of text re: the weather lag to the header in the model script. Let me know if you think that's sufficient or if I should add in an explanation of the lag elsewhere.

2018-02-08 18:44 UTC, gmyenni requested changes

2018-02-08 18:44 UTC, gmyenni commented on tools/model_functions.R
> +
This 'which_is_lagged' bit could use an explanation at the top

2018-02-08 18:44 UTC, gmyenni commented on tools/model_functions.R
> +
Yep, looks good to me!

2018-02-08 18:54 UTC, gmyenni commented
Okay, you could add the biological context I suggested above in the model header. 
And in model_functions.R you can add a reference back to the model use at the start of the lag section.

2018-02-08 20:07 UTC, gmyenni commented
I guess 'above' isn't really that helpful. :) I was saying you could add something like 'a 6-month lag black boxes the entire rain - resources - rodents process' to the model script header.

Overall though, I think this looks good. There are overarching issues with the lag stuff that is making the code unavoidably confusing and weird that we'll have to get to later.

2018-02-08 20:07 UTC, gmyenni approved these changes

2018-02-08 21:05 UTC, ethanwhite approved these changes

2018-02-09 00:05 UTC, DAPPERstats commented
I was having a difficult time figuring out how to resolve that conflict, as it wasn't letting me do it on the web interface and the instructions it gave me weren't working in the command line.
it looks like the conflict had to do with the removal of the old model file, so I added it back here for the merge and then will delete it in a new quick branch and merge off the new master. Note that in the quick interim, the build and check might break because of the change in the weather data.

2018-02-09 00:05 UTC, merged